disabled_rules:
  - trailing_whitespace
  - variable_name
  - valid_docs
  - shorthand_operator
  - void_return
  - redundant_discardable_let
  - unused_optional_binding

excluded:
  - Pods
  - AxxessCARETests
  - DuctTapeUITests

force_cast: warning

line_length:
  - 150 # Warning

function_body_length:
  - 150 # Warning
  - 250 # Error

reporter: "checkstyle"
